/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f7f9fb',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed-variant': '#003dab',
        'secondary-fixed': '#dce1ff',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#e7eeff',
        'on-surface': '#191c1e',
        'on-secondary': '#ffffff',
        'on-primary-container': '#ebedff',
        'on-surface-variant': '#424655',
        'on-tertiary-fixed': '#0e1c30',
        'surface-container': '#eceef0',
        'tertiary-fixed': '#d6e3ff',
        'tertiary': '#47546b',
        'inverse-surface': '#2d3133',
        'inverse-primary': '#b5c4ff',
        'on-background': '#191c1e',
        'primary': '#0f5ef7',
        'on-secondary-container': '#fffbff',
        'surface-dim': '#d8dadc',
        'outline': '#737687',
        'primary-container': '#0f5ef7',
        'surface-variant': '#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#5f6c84',
        'outline-variant': '#c3c5d8',
        'secondary-fixed-dim': '#b6c4ff',
        'primary-fixed-dim': '#b5c4ff',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'secondary': '#0d4edc',
        'surface-container-highest': '#e0e3e5',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eff1f3',
        'on-secondary-fixed': '#00164f',
        'on-secondary-fixed-variant': '#003bb0',
        'on-tertiary-fixed-variant': '#3a475d',
        'on-error': '#ffffff',
        'surface-tint': '#0052de',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed-dim': '#bac7e2',
        'surface-container-low': '#f2f4f6',
        'background': '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'on-primary-fixed': '#00174c',
        'secondary-container': '#3869f6',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'margin': '32px',
        'lg': '24px',
        'gutter': '24px',
        'xl': '32px',
        'base': '4px',
        'md': '16px',
        '2xl': '48px',
        'sm': '8px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}